cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('payment/', views.payment, name='payment'),
    path('payment/pay_now/<str:merchant_uid>', views.pay_now, name='pay_now'),
    path('payment/pay_complete/', views.pay_complete, name='pay_complete'),
]

happymoon/urls.py
from django.contrib import admin
from django.urls import include, path
from store import views
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('store/pad/', include('store.urls', namespace="store_pad")),
    path('store/goods/', include('goods.urls', namespace="store_goods")),
    path('', include('subscription.urls', namespace="subscription")),
    path('mypage/', include('mypage.urls', namespace="mypage")),
    path('store/cart/', include('cart.urls', namespace="cart")),
    path('review/', include('reviews.urls', namespace="reviews")),
    path('notice_list/', include('notice_list.urls', namespace="notice_list")),
    path('main/', include('main.urls'), name='main'),
    path('', lambda req: redirect('main:main'), name='root'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviews/urls.py
from django.urls import path
from . import views

app_name = 'reviews'

urlpatterns = [
    path('', views.review_list, name='review_list'),
    path('create/', views.review_create, name='review_create'),
]

reviews/models.py
from django.db import models
from django.conf import settings
from subscription.models import Type


# Create your models here.
class Review(models.Model):
    STAR_CHOICES = (
        (1, 1), (2, 2), (3, 3), (4, 4), (5, 5),
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    star = models.IntegerField(choices=STAR_CHOICES)
    #product = models.ForeignKey(Type, blank=True, null=True, on_delete=models.CASCADE) #TODO: 여기 __str__ 수정해야될까?
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        name = str(self.user)+"님의 후기 /"+str(self.created_at)
        return name


class Review_Comment(models.Model):
    review = models.ForeignKey(Review, on_delete=models.CASCADE,) #related_name="comment_set"
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

reviews/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from .models import Review, Review_Comment
from django.core.paginator import Paginator


# Create your views here.
# without-pagination Or digg-style
# def review_list(request):
#     reviews = Review.objects.all()
#     comments = Review_Comment.objects.all()
#
#     ctx = {
#         'reviews': reviews,
#         'comments': comments,
#     }
#     return render(request, 'reviews/review_list.html', ctx)


# django paginiatior
def review_list(request):
    all_reviews = Review.objects.all()
    all_reviews = all_reviews.order_by('-id')
    paginator = Paginator(all_reviews, 5)

    page = request.GET.get('page')
    reviews = paginator.get_page(page)
    ctx = {
        'reviews': reviews,
    }
    return render(request, 'reviews/review_list.html', ctx)


def review_create(request):
    if request.method == "POST":
        star = request.POST.get('star')
        title = request.POST.get('title')
        content = request.POST.get('content')
        review = Review()
        review.user = request.user
        review.star = star
        review.title = title
        review.content = content
        review.save()
        return redirect(reverse('reviews:review_list'))

    if not request.user.is_authenticated:
        return redirect(reverse("accounts:login"))
    return render(request, 'reviews/review_create.html')

reviews/templates/reviews/review_create.html
{% extends 'base.html' %}

{% block css %}
    <link rel="stylesheet" href="/static/css/reviews/review_create.css">
{% endblock %}

{% block main %}
<div class="top">
    <h1>해피문데이 실사용자 리뷰</h1>
</div>

<div class="create_wrap">
    <div class="create_container">
        <form method="post">
            {% csrf_token %}
            <table>
                <tr>
                    <td>별점</td>
                    <td>
                        <select name="star" id="star">
                            <option value=1>1</option>
                            <option value=2>2</option>
                            <option value=3>3</option>
                            <option value=4>4</option>
                            <option value=5>5</option>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td>제목</td>
                    <td><input name="title" type="text" class="title" placeholder="제목" id="title"></td>
                </tr>
                <tr>
                    <td>내용</td>
                    <td><textarea name="content" class="content" row="5" placeholder="내용"  id="content"></textarea></td>
                </tr>
            </table>
            <button class="btn" type="submit"> 리뷰남기기 </button>
        </form>
    </div>

</div>



{% endblock %}

reviews/templates/reviews/review_list.html
{% extends 'base.html' %}
{% load static %}
{% load el_pagination_tags %}

{% block css %}
    <link rel="stylesheet" href="/static/css/reviews/review_list.css">
{% endblock %}

{% block main %}
<div class="top">
    <h1>해피문데이 실사용자 리뷰</h1>
    <h2>후기가 궁금하신가요?</h2>
    <a class="btn-review" href="{% url 'reviews:review_create' %}">리뷰 남기기</a>
</div>


<!-- without pagination -->
{#<div class="reviews_container">#}
{#    {% for review in reviews %}#}
{#        <div class="reviewAndcomment">#}
{#            <div class="review">#}
{#                <ul>#}
{#                    <li#}
{#                    <li>{{ review.star }}</li>#}
{#                    <li>{{ review.user.username }} {{ review.created_at }}</li>#}
{#                    <li id="review_title">{{ review.title }} </li> <!--{{ review.product }}-->#}
{#                    <li>{{ review.content }}</li>#}
{#                </ul>#}
{#            </div>#}
{#            <div class="comment">#}
{#                {% for comment in review.review_comment_set.all %}#}
{#                    <ul>#}
{#                        <li>{{ comment.author }}</li>#}
{#                        <li>{{ comment.message }}</li>#}
{#                    </ul>#}
{#                {% endfor %}#}
{#            </div>#}
{#        </div>#}
{#    {% endfor %}#}
{#</div>#}


<!--pagination digg-style -->
{#<div class="reviews_container_pagination">#}
{#{% paginate 5 reviews %}#}
{#    {% for review in reviews %}#}
{#        <div class="reviewAndcomment">#}
{#            <div class="review">#}
{#                <ul>#}
{#                    <li>{{ review.star }}</li>#}
{#                    <li>{{ review.user.username }} {{ review.created_at }}</li>#}
{#                    <li id="review_title">{{ review.title }} </li> <!--{{ review.product }}-->#}
{#                    <li>{{ review.content }}</li>#}
{#                </ul>#}
{#            </div>#}
{#            <div class="comment">#}
{#                {% for comment in review.review_comment_set.all %}#}
{#                    <ul>#}
{#                        <li>{{ comment.author }}</li>#}
{#                        <li>{{ comment.message }}</li>#}
{#                    </ul>#}
{#                {% endfor %}#}
{#            </div>#}
{#        </div>#}
{#    {% endfor %}#}
{#</div>#}
{#    <div class="pages">#}
{#        {% show_pages %}#}
{#    </div>#}


<!--django pagination-->
<div class="reviews_container_pagination">
    {% for review in reviews %}
        <div class="reviewAndcomment">
            <div class="review">
                <ul>
                    <li>{{ review.star }}</li>
                    <li><b>{{ review.user.information.name }}</b> <small>{{ review.created_at |date:"Y.m.d."}}</small></li>
                    <li id="review_title">{{ review.title }} </li> <!--{{ review.product }}-->
                    <li>{{ review.content }}</li>
                </ul>
            </div>
            <div class="comment">
                {% for comment in review.review_comment_set.all %}
                    <ul>
                        <li class="superuser">
                            <img id="logo_symbol" src="{% static 'images/logo_symbol_happymoonday.png' %}">
                            <b>해피문데이</b><small>{{ comment.created_at |date:"Y.m.d."}}</small>
                        </li>
                        <li class="superuser_message">{{ comment.message }}</li>
                    </ul>
                {% endfor %}
            </div>
        </div>
    {% endfor %}
</div>

<div class="pages">
    <span class="step-links">
        {% if reviews.has_previous %}
{#            <a href="?page=1">&laquo; first</a>#}
            <a href="?page={{ reviews.previous_page_number }}"> 〈 </a>
        {% else %}
            <a> 〈 </a>
        {% endif %}

        <span class="current">
            <span class="current_now">{{ reviews.number }}</span>  &nbsp; &nbsp;/  &nbsp; &nbsp; {{ reviews.paginator.num_pages }}
        </span>

        {% if reviews.has_next %}
            <a href="?page={{ reviews.next_page_number }}"> 〉 </a>
{#            <a href="?page={{ reviews.paginator.num_pages }}">last &raquo;</a>#}
        {% else %}
            <a> 〉 </a>
        {% endif %}
    </span>
</div>



<div class="bottom">
    <div class="bottom_container">
        {{ a }}
        <p>좋은 제품으로 일상에 도움이 되고 싶어요</p>
        <p>좋은 생리대 편하게 편하게</p>
        <button>신청하기</button>
    </div>
</div>

{% endblock %}