cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('payment/', views.payment, name='payment'),
    path('payment/pay_now/<str:merchant_uid>', views.pay_now, name='pay_now'),
    path('payment/pay_complete/', views.pay_complete, name='pay_complete'),
]

cart_subscription/urls.py
from django.urls import path
from cart_subscription import views

app_name = 'cart_subscription'

urlpatterns = [
    path('', views.cart_subscription, name='cart_subscription'),
    path('payment/<str:merchant_uid>', views.payment, name='payment'),
    path('payment/pay_success/', views.pay_success, name='pay_success'),
]

happymoon/urls.py
from django.contrib import admin
from django.urls import include, path
from store import views
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('store/pad/', include('store.urls', namespace="store_pad")),
    path('store/goods/', include('goods.urls', namespace="store_goods")),
    path('', include('subscription.urls', namespace="subscription")),
    path('mypage/', include('mypage.urls', namespace="mypage")),
    path('store/cart/', include('cart.urls', namespace="cart")),
    path('review/', include('reviews.urls', namespace="reviews")),
    path('notice_list/', include('notice_list.urls', namespace="notice_list")),
    path('main/', include('main.urls'), name='main'),
    path('', lambda req: redirect('main:main'), name='root'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

subscription/urls.py
from django.urls import path, include
from . import views

app_name = 'subscription'

urlpatterns = [
    path('subscription/', views.subscription_list, name="subscription_list"),
    path('subscription_detail/HM-<str:str>/', views.subscription_detail, name="subscription_detail"),
]

cart_subscription/models.py
from django.db import models
from uuid import uuid4
from django.conf import settings


# Create your models here.
class Order_Subscription(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, verbose_name='주문상품')
    amount = models.PositiveIntegerField(verbose_name='총 결제금액')
    merchant_uid = models.UUIDField(default=uuid4, editable=False)  # uuid4 ; 임의의 id부여해줌/ 수정불가능하게 editable False
    imp_uid = models.CharField(max_length=100, blank=True)  # 결제완료된 후 받아오는 값이므로 처음에는 blank

    buyer_name = models.CharField(max_length=50, verbose_name='주문자 이름')
    buyer_email = models.CharField(max_length=100, verbose_name='주문자 이메일')
    buyer_tel = models.CharField(max_length=11, verbose_name='휴대폰번호')

    recipient_name = models.CharField(max_length=50, verbose_name='수령인 이름')
    recipient_tel = models.CharField(max_length=11, verbose_name='휴대폰번호')

    recipient_postcode = models.CharField(max_length=10, verbose_name='우_편번호')
    recipient_add = models.CharField(max_length=100, verbose_name='주소')
    recipient_add_detail = models.CharField(max_length=100, verbose_name='상세주소')
    recipient_memo = models.CharField(max_length=100, blank=True, null=True, verbose_name='배송메모(선택)')

cart_subscription/forms.py
from django import forms
from .models import Order_Subscription

class OrderForm_Subscription(forms.ModelForm):
    class Meta:
        model = Order_Subscription
        fields = ('name', 'amount', 'buyer_name', 'buyer_email', 'buyer_tel',
                    'recipient_name', 'recipient_tel', 'recipient_memo',)
        widgets = {
            'name': forms.HiddenInput,
            'amount': forms.HiddenInput,
            'buyer_name': forms.TextInput(attrs={'readonly': 'readonly'}),
            'buyer_email': forms.TextInput(attrs={'class': 'email', 'readonly': 'readonly'}),
            'buyer_tel': forms.TextInput(attrs={'placeholder': '휴대폰 번호'}),
            'recipient_name': forms.TextInput(attrs={'placeholder': '이름'}),
            'recipient_tel': forms.TextInput(attrs={'placeholder': '휴대폰 번호'}),
            'recipient_memo': forms.TextInput(attrs={'placeholder': '배송메시지'}),
        }

cart_subscription/views.py
from django.conf import settings
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.http import HttpResponse, Http404
from django.contrib.auth.decorators import login_required
from subscription.models import Cart_for_Subscription
from accounts.models import Information
from cart_subscription.forms import OrderForm_Subscription
from cart_subscription.models import Order_Subscription
from iamport import Iamport

iamport = Iamport(imp_key=settings.DEFAULT_TEST_IMP_KEY,
                  imp_secret=settings.DEFAULT_TEST_IMP_SECRET)


def cart_subscription(request, str):
    cart_subscriptions = Cart_for_Subscription.objects.filter(type_str=str)
    buyer = get_object_or_404(Information, user=request.user)
    name = cart_subscriptions[2] # 상품이름
    amount = cart_subscriptions[6] # 상품개수
    buyer_name = buyer.name
    buyer_email = buyer.email
    initial = {'name': name, 'amount': amount, 'buyer_name': buyer_name, 'buyer_email': buyer_email}

    if (request.method == 'POST'):
        form = OrderForm_Subscription(request.POST, initial=initial)
        if request.user.is_authenticated and form.is_valid():
            order = form.save(commit=False)
            recipient_postcode = request.POST.get('recipient_postcode')
            recipient_add = request.POST.get('recipient_add')+' '+request.POST.get('recipient_adddetail')
            order.recipient_postcode = recipient_postcode
            order.recipient_add = recipient_add
            order.user = request.user
            order.save()

            return redirect(reverse('cart_subscription:payment', args=(str(order.merchant_uid), )))

        elif not (request.user.is_authenticated):
            return redirect(reverse("accounts:login"))

        elif not (form.is_valid):
            print(form)
            return HttpResponse('결제 실패')

    else:
        form = OrderForm_Subscription(initial=initial)

    ctx = {
        'form': form,
        'cart_subscriptions': cart_subscriptions,
    }
    return render(request, "cart_subscription.html", ctx)

def payment(request, merchant_uid):
    order = Order_Subscription.objects.get(user=request.user, merchant_uid=merchant_uid)
    ctx = {
        'iamport_shop_id': 'iamport',
        'order': order,
    }
    return render(request, 'payment.html', ctx)

def pay_success(request):
    imp_uid = request.GET.get("imp_uid")
    response = iamport.find_by_imp_uid(imp_uid)

    merchant_uid = response["merchant_uid"]
    myorder = get_object_or_404(Order_Subscription, merchant_uid=merchant_uid)
    myorder.imp_uid = imp_uid
    myorder.save()

    type_price = myorder.amount
    if not iamport.is_paid(type_price, imp_uid=imp_uid):
        # 결제실패
        return HttpResponse('실패')

    return render(request, 'pay_success.html')

cart_subscription/templates/cart_subscription.html
{% extends 'base.html'%}

{% block css%}
  <link rel="stylesheet" href="/static/css/login/default.css">
  <link rel="stylesheet" href="/static/css/cart_subscription/cart_subscription.css">
{% endblock%}


{% block main %}

<div id="main">
    <div class="cart_container">
        <h2>정기배송 주문내역</h2>

    <!-- 정기배송 주문내역 리스트 -->

        <div class="list_container">

            <div class="list_head">
                <div class="name">상품</div>
                <div class="qty">수량</div>
                <div class="pads">총 수량</div>
                <div class="item_total">총 가격</div>
            </div>

            <div class="list_item">
                <div class="name_price_container">
                    <div class="thumbnail"><img src="{{ cart_subscription.type.img.url }}" width=100px></div>
                    <div class="name">{{ cart_subscription.type_str }}. {{ cart_subscription.type.type }}</div>
                </div>
                <div class="qty">{{ cart_subscription.number }}</div>
                <div class="pads">{{ cart_subscription.component }}</div>
                <div class="item_total">{{ cart_subscription.price }}원</div>
            </div>

            <div class="list_item">
                <div class="name_price_container">
                    <div class="thumbnail"><img src="/static/images/ic_calendar.png" class="ic_date"></div>
                    <div class="name">
                        첫 발송일: <script language="JavaScript">
                                      var today = new Date()
                                      document.write(today.getYear()+1900, "년 ", today.getMonth()+1, "월 ", today.getDate()+1, '일')
                                   </script>
                        <br>
                        배송주기: {{ cart_subscription.delivery_period}}</div>
                </div>
                <div class="qty"></div>
                <div class="item_total"></div>
            </div>

            <a href="/subscription_detail/HM-{{ cart_subscription.type_str }}" class="button_gray">주문 변경</a>

        </div>

     <form action="" method="POST">
        {% csrf_token %}
        <!-- 주문자 정보 -->
        <div class="user_info">
            <h2>주문자 정보</h2>
            <table>
                <tr>
                    <td>이름</td>
                    <td>{{ form.buyer_name }}</td>
                </tr>
                <tr>
                    <td>이메일</td>
                    <td>{{ form.buyer_email }}</td>
                </tr>
                <tr>
                    <td>휴대폰번호</td>
                    <td>{{ form.buyer_tel }}</td>
                </tr>
                <tr>
                    <td>{{ form.name }}</td>
                    <td>{{ form.amount }}</td>
                </tr>
            </table>
        </div>

        <!-- 배송지 정보 -->
        <div class="address_info">
            <h2>배송지 정보</h2>
            <table>
                <tr>
                    <td>이름</td>
                    <td>{{ form.recipient_name }}</td>
                </tr>
                <tr>
                    <!--TODO: 휴대폰인증-->
                    <td>휴대폰번호</td>
                    <td>{{ form.recipient_tel }}</td>
                </tr>
                <tr>
                    <!--TODO: 주소API-->
                    <td>주소</td>
                    <td>
                        <input name="recipient_postcode" type="text" id="sample6_postcode" placeholder="우편번호">
                        <input type="button" onclick="sample6_execDaumPostcode()" value="우편번호 찾기"><br>
                    </td>
                </tr>

                <tr>
                    <td></td>
                    <td><input name="recipient_add" type="text" id="sample6_address" placeholder="주소"></td>
                </tr>
                <tr>
                    <td></td>
                    <td><input name="recipient_adddetail" type="text" id="sample6_address2" placeholder="상세주소"></td>
                </tr>

{#                    <td>{{ form.recipient_postcode }}</td>#}
{#                    <td>{{ form.recipient_add }}</td>#}

                <tr>
                    <td>배송 메모 (선택)</td>
                    <td>{{ form.recipient_memo }}</td>
                </tr>
            </table>
        </div>

         <!-- 할인 수단 -->

        <!--  결제하기 -->
        <div class="pay">
            <h2>최종 결제금액</h2>
            <table class="total_price">
                <tbody>
                    <tr><td>총 상품가격</td><td>{{ cart_subscription.price }}원</td></tr>
                    <tr><td>배송비</td><td>무료</td></tr>
                    <tr><td>총 결제금액</td><td>{{ cart_subscription.price }}원</td></tr>
                </tbody>
            </table>
            <input type='hidden' name='post_type' value='pay'>
            <button type="submit" class="">결제하기</button>
        </div>
    </form>


</div>

    <!-- 다음주소 API -->
    <script src="http://dmaps.daum.net/map_js_init/postcode.v2.js"></script>

    <script>
        function sample6_execDaumPostcode() {
            new daum.Postcode({
                oncomplete: function(data) {
                    // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.
                    // 각 주소의 노출 규칙에 따라 주소를 조합한다.
                    // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.
                    var fullAddr = ''; // 최종 주소 변수
                    var extraAddr = ''; // 조합형 주소 변수
                    // 사용자가 선택한 주소 타입에 따라 해당 주소 값을 가져온다.
                    if (data.userSelectedType === 'R') { // 사용자가 도로명 주소를 선택했을 경우
                        fullAddr = data.roadAddress;
                    } else { // 사용자가 지번 주소를 선택했을 경우(J)
                        fullAddr = data.jibunAddress;
                    }
                    // 사용자가 선택한 주소가 도로명 타입일때 조합한다.
                    if(data.userSelectedType === 'R'){
                        //법정동명이 있을 경우 추가한다.
                        if(data.bname !== ''){
                            extraAddr += data.bname;
                        }
                        // 건물명이 있을 경우 추가한다.
                        if(data.buildingName !== ''){
                            extraAddr += (extraAddr !== '' ? ', ' + data.buildingName : data.buildingName);
                        }
                        // 조합형주소의 유무에 따라 양쪽에 괄호를 추가하여 최종 주소를 만든다.
                        fullAddr += (extraAddr !== '' ? ' ('+ extraAddr +')' : '');
                    }
                    // 우편번호와 주소 정보를 해당 필드에 넣는다.
                    document.getElementById('sample6_postcode').value = data.zonecode; //5자리 새우편번호 사용
                    document.getElementById('sample6_address').value = fullAddr;
                    // 커서를 상세주소 필드로 이동한다.
                    document.getElementById('sample6_address2').focus();
                }
            }).open();
        }
    </script>

        <!-- Shipping Detail -->

{#        <form action="" method="post">#}
{#            <div class="shipping_container">#}
{##}
{#                <input type="hidden">#}
{#                <input type="hidden" name="post_type" value="payment">#}
{#                <input type="hidden" id="purchase_type" name="purchase_type" value="subscription">#}
{##}
{#                <div class="column-shipping">#}
{#                    <!-- Order User -->#}
{#                    <h3>#}
{#                        <div class="shipping_circle">#}
{#                            <img src="/static/images/ic_payment_order_user.png">#}
{#                        </div>#}
{#                        주문자 정보#}
{#                    </h3>#}
{#                    <div class="deliver_option_wrap">#}
{#                        <div class="deliver_option_half">#}
{#                            <p class="label">이름<span class="required">*</span></p>#}
{#                            <input type="text" id="name" name="name" placeholder="이름" maxlength="20" class="input_default" value="이름">#}
{#                        </div>#}
{#                        <div class="deliver_option_half">#}
{#                            <p class="label">이메일<span class="required">*</span></p>#}
{#                            <input type="email" id="email" name="email" placeholder="이메일" maxlength="100" class="input_default" value="이메일">#}
{#                        </div>#}
{#                        <div class="deliver_option_half">#}
{#                            <p class="label">휴대폰번호<span class="required">*</span></p>#}
{#                            <input type="tel" id="phone" name="phone" placeholder="- 없이 숫자만 입력해주세요" maxlength="11" class="input_default_phone numbersOnly">#}
{#                            <div id="button_phone_verification_request" class="button_phone_certify">인증요청</div>#}
{#                        </div>#}
{#                    </div>#}
{#                    <!-- Destination -->#}
{#                    <h3>#}
{#                        <div class="shipping_circle">#}
{#                            <img src="/static/images/ic_payment_destination.png">#}
{#                        </div>#}
{#                        배송지 정보#}
{#                    </h3>#}
{#                    <div class="deliver_option_wrap">#}
{#                        <div class="deliver_option_half">#}
{#                            <p class="label">이름<span class="required">*</span></p>#}
{#                            <p id="error_name_len" class="error_message" style="display: none;">#}
{#                                이름을 2글자 이상 입력해주세요.#}
{#                            </p>#}
{#                            <input type="text" id="recipient_name" name="recipient_name" placeholder="이름" maxlength="20" class="input_default" value="이름">#}
{#                        </div>#}
{#                        <div class="deliver_option_half">#}
{#                            <p class="label">휴대폰번호<span class="required">*</span></p>#}
{#                            <input type="tel" id="recipient_phone" name="recipient_phone" placeholder="- 없이 숫자만 입력해주세요" maxlength="11" class="input_default">#}
{#                        </div>#}
{#                        <div class="deliver_option">#}
{#                            <p class="label">주소<span class="required">*</span></p>#}
{#                            <p id="error_addr_check" class="error_message" style="display: none;">#}
{#                                우편번호 찾기를 진행해주세요.#}
{#                            </p>#}
{#                            <input type="text" id="zip_code" name="zip_code" placeholder="우편번호" maxlength="6" class="input_default_post" value readonly="readonly">#}
{#                            <input type="button" onclick="execDaumPostcode()" value="우편번호 찾기" class="button_find_post">#}
{#                            <br>#}
{#                            <div id="wrap" style="display: none;position:relative;" ></div>#}
{#                            <input type="text" id="address_1" name="address_1" placeholder="주소" maxlength="120" class="input_default" value readonly="readonly">#}
{#                            <input type="text" id="address_1" name="address_2" placeholder="상세주소" maxlength="120" class="input_default" value>#}
{#                            <p class="label">배송 메모 (선택)</p>#}
{#                            <input type="text" id="delivery_message" name="delivery_message" placeholder="배송메시지" maxlength="50" class="input_default" value>#}
{#                        </div>#}
{#                    </div>#}
{#                    <!-- Discount 여기 하는 중이었음 -->#}
{#                    <h3></h3>#}
{#                    <div class="deliver_option_wrap">#}
{##}
{#                    </div>#}
{##}
{##}
{#                </div>#}
{##}
{#                <div class="column-payment">#}
{#                    <div id="total_order_summary_container" class="total_order_summary_container">#}
{##}
{#                    </div>#}
{#                </div>#}
{##}
{#            </div>#}
{#        </form>#}

</div>

{%  endblock %}

cart_subscription/templates/pay_success.html
{% extends 'base.html' %}

{% block main %}
    <h1 style="text-align:center;">결제 성공</h1>
{% endblock %}

cart_subscription/templates/payment.html
{% extends 'base.html'%}

{% block main%}
<h1 style="text-align:center;">결제진행중</h1>

<script src="http://code.jquery.com/jquery-1.12.4.min.js" ></script>
<script src="http://service.iamport.kr/js/iamport.payment-1.1.5.js"></script>
<script>
(function() {
    var IMP = window.IMP;
    var code = "iamport";  // FIXME: 가맹점 식별코드 (로그인/시스템설정/내정보)
    IMP.init(code);
    // 결제요청
    IMP.request_pay({
        pg : 'html5_inicis', //pg사 변경 가능
        pay_method : 'card',
        merchant_uid : '{{ order.merchant_uid }}',
        name : '{{ order.name }}',
        amount : {{ order.amount }},
        buyer_email : '{{ order.buyer_email }}',
        buyer_name : '{{ order.buyer_name }}',
        buyer_tel : '{{ order.buyer_tel }}',
        //buyer_addr : '서울특별시 강남구 삼성동',
        //buyer_postcode : '123-456',
        m_redirect_url : '{% url "cart_subscription:pay_success" %}'
    }, function(rsp) {
        if ( rsp.success ) {
            var msg = '결제가 완료되었습니다.';
            //msg += '고유ID : ' + rsp.imp_uid; //iamport에서 결정해주는 고유 아이디
            //msg += '상점 거래ID : ' + rsp.merchant_uid; //상점아이디
            //msg += '결제 금액 : ' + rsp.paid_amount;
            //msg += '카드 승인번호 : ' + rsp.apply_num;

            var imp_uid = rsp.imp_uid;
            location.href = '{% url "cart_subscription:pay_success" %}?imp_uid='+imp_uid;
        }
        else {
            var msg = '결제에 실패하였습니다. 에러내용 : ' + rsp.error_msg;
        }
        alert(msg);
    });
})();
</script>

{% endblock %}




<!--  extra body for js-->
<script src="//code.jquery.com/jquery-1.12.4.min.js" ></script>
<script src="https://service.iamport.kr/js/iamport.payment-1.1.5.js"></script>
<script>
$(function() {
    var $form = $('#order_subscription-form');
    var params = {
        name: $form.find('[name=name]').val(),
        amount: $form.find('[name=amount]').val(),
    };
    IMP.init('{{ iamport_shop_id }}');
    IMP.request_pay(params, function(response_data) {
        console.log('response_data :', response_data);
        if ( ! response_data.success ) {
            alert(response_data.error_msg + "(" + response_data.error_code + ")");
            location.href = '{% url "subscription:subscription_list" %}';
        }
        else {
            $.each(response_data, function(key, value) {
                $form.find("input[name=" + key + "]").val(value);
            });
            $form.submit();
        }
    });
});
</script>