cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('payment/', views.payment, name='payment'),
    path('payment/pay_now/<str:merchant_uid>', views.pay_now, name='pay_now'),
    path('payment/pay_complete/', views.pay_complete, name='pay_complete'),
]

happymoon/urls.py
from django.contrib import admin
from django.urls import include, path
from store import views
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('store/pad/', include('store.urls', namespace="store_pad")),
    path('store/goods/', include('goods.urls', namespace="store_goods")),
    path('', include('subscription.urls', namespace="subscription")),
    path('mypage/', include('mypage.urls', namespace="mypage")),
    path('store/cart/', include('cart.urls', namespace="cart")),
    path('review/', include('reviews.urls', namespace="reviews")),
    path('notice_list/', include('notice_list.urls', namespace="notice_list")),
    path('main/', include('main.urls'), name='main'),
    path('', lambda req: redirect('main:main'), name='root'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name = 'store_pad'

urlpatterns = [
    path('', views.product_list, name='pad_list'),
    path('<int:pk>/', views.product_detail, name='pad_detail'),
    #path('cart/', views.cart_for_pad, name='cart_for_pad'),
]

store/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings


# Create your models here.
class Product(models.Model):
    img_front = models.ImageField(upload_to = 'store/', blank=True)
    img_back = models.ImageField(upload_to = 'store/', blank=True)
    img_inner = models.ImageField(upload_to = 'store/', blank=True)
    img_side = models.ImageField(upload_to = 'store/', blank=True)
    # p_code = models.IntegerField(blank=True)
    name = models.CharField(max_length=20)
    price = models.IntegerField()
    detail = models.TextField()
    volume = models.IntegerField()
    size = models.IntegerField()
    manufac_date = models.CharField(max_length=30)
    useby_date = models.CharField(max_length=30)
    quantity = models.IntegerField()
    ingre = models.TextField()

    def __str__(self):
        return self.name

#   order = models.OneToOneField('store.Cart')

class Cart_for_Pad(models.Model):
    user= models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    order = models.IntegerField()
    total_price = models.IntegerField()
    checked = models.BooleanField(default=False)

store/views.py
from django.shortcuts import render,reverse, redirect
from .models import Product, Cart_for_Pad
from django.db.models import Q
# from django.contrib.auth import User
import random

# Create your views here.
def product_list(request):
  products = Product.objects.all()
  ctx={
    'products':products,
  }
  return render(request,'store/product_list.html', ctx)


def product_detail(request, pk):
    product = Product.objects.get(pk=pk)
    if request.method == 'POST':

        user = request.user
        order = request.POST.get('order')
        total_price = int(product.price) * int(order)
        print(total_price)
        cart = Cart_for_Pad.objects.create(
            user = user,
            product = product,
            order = order,
            total_price = total_price,
        )

        return  redirect(reverse('cart:cart'))

        if request.user.is_authenticated:
            user = request.user
            order = request.POST.get('order')
            total_price = int(product.price) * int(order)
            print(total_price)
            cart = Cart_for_Pad.objects.create(
                user = user,
                product = product,
                order = order,
                total_price = total_price,
                )
        else:
            user= None
            order = request.POST.get('order')
            total_price = int(product.price) * int(order)
            print(total_price)
            cart = Cart_for_Pad.objects.create(
                user=user,
                product=product,
                order=order,
                total_price=total_price,
            )

            return redirect(reverse('cart:cart'))


    else:
        random_num=[]
        for i in range(1,len(Product.objects.all())+1):
            random_num.append(i)
        del random_num[pk-1]
        random.shuffle(random_num)

        products = Product.objects.filter(Q(pk=random_num[0])|Q(pk=random_num[1])|Q(pk=random_num[2]))
        ctx={
            'product' : product,
            'products' : products,
        }
        return render(request,'store/product_detail.html', ctx)


def cart_for_pad(request):
    cart = Cart_for_Pad.objects.all()
    ctx = {
        'cart': cart,
    }
    return render(request, 'store/cart_for_pad.html', ctx)

store/templates/store/cart_for_pad.html
{% extends 'base.html'%}

{% block css%}
  <link rel="stylesheet" href="/static/css/store/css_cart_for_pad.css">
{% endblock%}


{% block main %}
  <table class="cart_list">
    <thead>
      <tr>
        <th scope="col">상품</th>
        <th scope="col">가격</th>
        <th scope="col">수량</th>
        <th scope="col">총가격</th>
      </tr>
    </thead>
    <tbody>
      {% for cartunit in cart %}
      <tr>
        <td><a href={% url 'store_pad:pad_detail' cartunit.product.pk %}>{{ cartunit.product.name }}</a></td>
        <td>{{ cartunit.product.price }}원</td>
        <td>{{ cartunit.order }}</td>
        <td>~원</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

store/templates/store/product_detail.html
{% extends 'base.html'%}

{% block css%}
  <link rel="stylesheet" href="/static/css/store/css_product_detail.css">
{% endblock%}


{% block main %}
  <main>
    <div class="store_nav">
      <div class="nav_container">
        <h2 class="nav_left">스토어</h2>
        <div class="nav_category">
          <a href="/store/pad/" style="border-bottom:1px solid #000;">생리대</a>
          <a href=>굿즈</a>
          <a href=>정기배송</a>
        </div>
      </div>
    </div>

    <!-- Products Detail-->
    <div class="product_container">
      <div class="product_wrap">
        <div class="photo_container">
          <div>
            <img src="{{ product.img_front.url }}" width=570px;>
          </div>
        </div>
        <div class="spec_container">
          <h2>{{ product.name }}</h2>
          <p id="price">{{ product.price }}원</p>
          <p class="description">{{ product.detail }}</p>
          <table class="spec">
            <tbody>
              <tr><td>월경량</td><td>{{ product.volume }}</td></tr>
              <tr><td>사이즈</td><td>{{ product.size }}mm</td></tr>
              <tr><td>제조일자</td><td>{{ product.manufac_date }}</td></tr>
              <tr><td>사용기한</td><td>{{ product.useby_date }}</td></tr>
              <tr><td>1팩당 개수</td><td>{{ product.quantity }}</td></tr>
              <tr><td class="ingre">주요성분</td><td class="ingre">{{ product.ingre }}</td></tr>
            </tbody> 
          </table>
          
          <form action="" method="post" onsubmit="return validation()">
              {% csrf_token %}
              <div class="order">
                <label for="order">수량</label>
                <input name="order" id="order" type="order" class="order">
                  <p id="order_error" class="error_message"> </p>
                    <button type="submit" id="add_to_cart" class="button_cart">
                        <div>장바구니 담기 </div>
                    </button>
              </div>

          </form>
          {% comment %} <table class="quantity">
            <tbody><tr>
              <td class="text">수량</td>
              <td class="qty">
                <div class="qty_button">
                  <input type="button" value="-" class="qty_minus" onfocus="this.blur();">
                  <input type="number" step="1" min="1" value="1" class="qty_number" size="4" pattern="[0-9]*" inputmode="numeric" readonly="readonly" onfocus="this.blur();">
                  <input type="button" value="+" class="qty_plus" onfocus="this.blur();">
                </div>
              </td>
            </tr></tbody>
          </table> {% endcomment %}
          

        </div>
      </div>
    </div>

    <!-- Detail Description -->
    <div class="detail_description">
      <div class="row1">
        <div class="pic1">
          <img src="/static/images/store/store_detail_photo1.jpg">
        </div>
        <div class="txt1">
          <img id="txt1_1" src="/static/images/store/store_detail_text1.png">
          <img id="txt1_2" src="/static/images/store/mark_ocs.png">
        </div>
      </div>
      <div class="row2">
        <div class="txt2">
          <img id="txt2_1" src="/static/images/store/store_detail_text2.png">
          <div id="txt2_2_button_wrap">
            <div id="txt2_2_button">제품 상세보기</div>
          </div>
        </div>
        <div class="pic2">
          <img src="/static/images/store/store_detail_photo2.jpg">
        </div>
      </div>
    </div>


    <!-- Detail Photo -->
    <div class="detail_photo">
      <h1>DETAIL</h1>
      <img src="{{ product.img_front.url }}">
      <img src="{{ product.img_back.url }}">
      <img src=" {{ product.img_inner.url }}">
      <img src="{{ product.img_side.url }}">
    </div>

    <!-- Recommend Items -->
    <div class="recommend_items">
      <h1>이 제품도 써보세요</h1>
      <div class="recommend_items_wrap">
        {% for item in products %}
          <a href="">
            <img src="{{ item.img_front.url }}">
            <p>{{ item.name }}</p>
            <p>{{ item.price }}원</p>
          </a>
        {% endfor %}
      </div>
    </div>


    <!-- Subscription Banner -->
    <div class="banner_subscription">
      <div class="cover_left"></div>
      <div class="cover_wrap">
        <div class="cover_title_container">
          <p>
          안심하고 쓸 수 있는<br>
          유기농 생리대로<br>
          월경주기에 맞춰 배송합니다.<br>
          </p>
          <a href="">정기배송 시작하기</a>
          <p class="shipping_free">(무료배송)</p>
        </div>
      </div>
      <div class="cover_right"></div>
    </div>
  </main>


    <script src="/static/js/jquery.js"></script>

<script>

function validation(){

var order = document.getElementById('order').value;
if(order == "") {
    document.getElementById('order_error').innerHTML =" 수량을 1 이상 입력하세요.";
    return false;
}}
</script>

{% endblock %}

store/templates/store/product_list.html
{% extends 'base.html'%}

{% block css%}
  <link rel="stylesheet" href="/static/css/store/css_product_list.css?ver=1.1">
  {% endblock%}


{% block main %}
  <main>
    <div class="store_nav">
      <div class="nav_container">
        <h2 class="nav_left">스토어</h2>
        <div class="nav_category">
          <a href="/store/pad/" style="border-bottom:1px solid #000;">생리대</a>
          <a href="/store/goods/">굿즈</a>
          <a href="/subscription/">정기배송</a>
        </div>
      </div>
    </div>

    <!--products_list-->
    <div class="wrap_container">
      <div class="item_container">
        
        {% for product in products %}
        <a href="{{ product.pk }}" class="item">
          <img src="{{ product.img_front.url }}" width=300px;>
          <p> {{ product.name }} </p>
          <p> {{ product.price }}원</p>
        </a>
        {% endfor %}
      </div>
    </div>
    <div class="banner_subscription">
      <div class="cover_left"></div>
      <div class="cover_wrap">
        <div class="cover_title_container">
          <p>
          해피문데이는<br>
          안심하고 쓸 수 있는 생리대를 만들고<br>
          월경주기에 맞춰 배송합니다.<br>
          </p>
          <a href="">정기배송 시작하기</a>
          <p class="shipping_free">(무료배송)</p>
        </div>
      </div>
      <div class="cover_right"></div>
    </div>
  </main>
  
{% endblock %}