cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('payment/', views.payment, name='payment'),
    path('payment/pay_now/<str:merchant_uid>', views.pay_now, name='pay_now'),
    path('payment/pay_complete/', views.pay_complete, name='pay_complete'),
]

happymoon/urls.py
from django.contrib import admin
from django.urls import include, path
from store import views
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('store/pad/', include('store.urls', namespace="store_pad")),
    path('store/goods/', include('goods.urls', namespace="store_goods")),
    path('', include('subscription.urls', namespace="subscription")),
    path('mypage/', include('mypage.urls', namespace="mypage")),
    path('store/cart/', include('cart.urls', namespace="cart")),
    path('review/', include('reviews.urls', namespace="reviews")),
    path('notice_list/', include('notice_list.urls', namespace="notice_list")),
    path('main/', include('main.urls'), name='main'),
    path('', lambda req: redirect('main:main'), name='root'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name = 'store_pad'

urlpatterns = [
    path('', views.product_list, name='pad_list'),
    path('<int:pk>/', views.product_detail, name='pad_detail'),
    #path('cart/', views.cart_for_pad, name='cart_for_pad'),
]

cart/models.py
from django.db import models
from uuid import uuid4
from django.conf import settings

# Create your models here.
class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, verbose_name='주문상품')
    amount = models.PositiveIntegerField(verbose_name='총 결제금액')
    merchant_uid = models.UUIDField(default=uuid4, editable=False) #uuid4 ; 임의의 id부여해줌/ 수정불가능하게 editable False
    imp_uid = models.CharField(max_length=100, blank=True) #결제완료된 후 받아오는 값이므로 처음에는 blank

    buyer_name = models.CharField(max_length=50, verbose_name='주문자 이름')
    buyer_email = models.CharField(max_length=100, verbose_name='주문자 이메일')
    buyer_tel = models.CharField(max_length=11, verbose_name='휴대폰번호')
    
    recipient_name = models.CharField(max_length=50, verbose_name='수령인 이름')
    recipient_tel = models.CharField(max_length=11, verbose_name='휴대폰번호')

    recipient_postcode = models.CharField(max_length=10, verbose_name='우_편번호')
    recipient_add = models.CharField(max_length=100, verbose_name='주소')
    recipient_add_detail = models.CharField(max_length=100, verbose_name='상세주소')
    recipient_memo = models.CharField(max_length=100, blank=True, null=True, verbose_name='배송메모(선택)')

    #status
    #created_at
    #updated_at

cart/forms.py
from django import forms
from .models import Order

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ('name', 'amount', 'buyer_name', 'buyer_email', 'buyer_tel',
                    'recipient_name', 'recipient_tel', 'recipient_memo',)
        widgets = {
            'name': forms.HiddenInput,
            'amount': forms.HiddenInput,
            'buyer_name': forms.TextInput(attrs={'readonly': 'readonly'}),
            'buyer_email': forms.TextInput(attrs={'class': 'email', 'readonly': 'readonly'}),
            'buyer_tel': forms.TextInput(attrs={'placeholder': '휴대폰 번호'}),
            'recipient_name': forms.TextInput(attrs={'placeholder': '이름'}),
            'recipient_tel': forms.TextInput(attrs={'placeholder': '휴대폰 번호'}),
            'recipient_memo': forms.TextInput(attrs={'placeholder': '배송메시지'}),
        }

cart/views.py
from django.conf import settings
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.http import HttpResponse, Http404
from django.contrib.auth.decorators import login_required
from store.models import Cart_for_Pad
from accounts.models import Information
from .forms import OrderForm
from .models import Order
from iamport import Iamport

iamport = Iamport(imp_key=settings.DEFAULT_TEST_IMP_KEY,
                  imp_secret=settings.DEFAULT_TEST_IMP_SECRET)


def cart(request):
    if (request.method == 'POST') and (request.POST.get('post_type') == 'order'):
        if request.user.is_authenticated:
            return redirect(reverse("cart:payment"))
        else:
            return redirect(reverse("accounts:login"))

    if (request.method == 'POST') and (request.POST.get('post_type') == 'select'):
        checked = request.POST.getlist('checked')
        for i in range(1, len(checked)+1):
            if (Cart_for_Pad.objects.get(id=checked[i-1])):
                    Cart_for_Pad.objects.get(id=checked[i-1]).delete()


    if request.user.is_authenticated:
        cart_products = Cart_for_Pad.objects.filter(user=request.user)
        ulti_total_price = 0
        for item in cart_products:
            ulti_total_price += item.total_price
        if ulti_total_price < 20000:
            shipping_charge = 2500
        else:
            shipping_charge = 0
        amount = (ulti_total_price + shipping_charge)
        ctx = {
            'cart_products': cart_products,
            'ulti_total_price': ulti_total_price,
            'shipping_charge': shipping_charge,
            'amount': amount,
            }
    else:
        cart_products = Cart_for_Pad.objects.filter(user=None)
        ulti_total_price = 0
        for item in cart_products:
            ulti_total_price += item.total_price
        if ulti_total_price < 20000:
            shipping_charge = 2500
        else:
            shipping_charge = 0
        amount = (ulti_total_price + shipping_charge)
        ctx = {
            'cart_products': cart_products,
            'ulti_total_price': ulti_total_price,
            'shipping_charge': shipping_charge,
            'amount': amount,
        }
    return render(request, "cart.html", ctx)


def payment(request): #TODO: 여기 이어서 하기
    items = Cart_for_Pad.objects.filter(user=request.user)
    buyer = get_object_or_404(Information, user=request.user)
    name = items[0].product.name+" 외 {}개".format(len(items)-1)
    ulti_total_price = 0
    for item in items:
        ulti_total_price += item.total_price
    if ulti_total_price < 20000:
            shipping_charge = 2500
    else:
        shipping_charge = 0
    amount = (ulti_total_price + shipping_charge)
    buyer_name = buyer.name
    buyer_email = buyer.email
    initial = {'name':name, 'amount':amount, 'buyer_name':buyer_name, 'buyer_email':buyer_email}

    if request.method == 'POST':
        form = OrderForm(request.POST, initial=initial)
        if form.is_valid(): #TODO: 여기가 문제===================
            order = form.save(commit=False)

            recipient_postcode = request.POST.get('recipient_postcode')
            recipient_add = request.POST.get('recipient_add')+' '+request.POST.get('recipient_adddetail')
            order.recipient_postcode = recipient_postcode
            order.recipient_add = recipient_add
            order.user = request.user
            order.save()
            return redirect(reverse('cart:pay_now', args=(str(order.merchant_uid),)))
        else:
            print(form)
            return HttpResponse("실패")
    else:
        form = OrderForm(initial=initial)
    
    cart_products = Cart_for_Pad.objects.filter(user=request.user)
    ctx = {
        'form': form,
        'cart_products': cart_products,
        'ulti_total_price': ulti_total_price,
        'shipping_charge': shipping_charge,
        'amount': amount,
    }
    return render(request, 'payment.html', ctx)


def pay_now(request, merchant_uid):
    order = Order.objects.get(user=request.user, merchant_uid=merchant_uid)
    ctx = {
        'iamport_shop_id': 'iamport',
        'order': order,
    }
    return render(request, 'pay_now.html', ctx)

# @login_required
# def order_new(request, item_id):
#     item = get_object_or_404(Item, pk=item_id)
#     order = Order.objects.create(user=request.user, item=item, name=item.name, amount=item.amount)
#     return redirect('shop:order_pay', item_id, str(order.merchant_uid)) #결제페이지로...


def pay_complete(request):
    imp_uid = request.GET.get("imp_uid")
    response = iamport.find_by_imp_uid(imp_uid)

    merchant_uid = response["merchant_uid"]
    myorder = get_object_or_404(Order, merchant_uid=merchant_uid)
    myorder.imp_uid = imp_uid
    myorder.save()

    # 장바구니 비우기
    Cart_for_Pad.objects.filter(user=request.user).delete()


    product_price = myorder.amount
    if not iamport.is_paid(product_price, imp_uid=imp_uid):
        # 결제실패
        return HttpResponse('실패')

    return render(request, 'pay_complete.html')

cart/templates/cart.html
{% extends 'base.html'%}

{% block css%}
  <link rel="stylesheet" href="/static/css/login/default.css">
  <link rel="stylesheet" href="/static/css/cart/cart_temp.css">
{% endblock%}


{% block main %}

<div id="main">
    <h1>장바구니</h1>

    <!-- 장바구니 리스트 -->
            <form action="" method="post">
                {% csrf_token %}
    <div class="carttable_container">
        <table class="carttable"style="width:100%">
                <tr>
                    <th> </th>
                    <th>상품</th>
                    <th>가격</th> 
                    <th>수량</th>
                    <th>총가격</th>
                </tr>
                {%if cart_products %}
                    {% for cart_product in cart_products %}
                    <tr>
                       <td><input id="checked" type="checkbox" name="checked" value={{ cart_product.id }}></td>
                        <td><img src="{{ cart_product.product.img_front.url }}" width=100px> {{ cart_product.product.name }}</td>
                        <td>{{ cart_product.product.price }}원</td> 
                        <td>{{ cart_product.order }}</td>
                        <td>{{ cart_product.total_price }}원</td>
                    </tr>
                    {% endfor %}
                {% else %}
                    <tr>
                        <td>장바구니가 비었습니다.</td>
                    </tr>
                {% endif %}            
        </table>


            <input type='hidden' name='post_type' value='select' />
            <button type="submit" class="">선택삭제</button>
       </div>
        </form>

    

    <!-- 주문하기 -->
    <div class="order_container">
        <table class="total_price">
            <tbody>
                <tr><td>총 상품가격</td><td>{{ ulti_total_price }}원</td></tr>
                <tr><td>배송비</td><td>{{ shipping_charge }}원</td></tr>
                <tr><td>총 결제금액</td><td>{{ amount }}</td></tr>
            </tbody> 
        </table>
        
        <p>20,000원 이상 구매 시 무료배송 / 제주지역 추가 3,000원</p>
        <form action="" method="post">
            {% csrf_token %}
            <input type='hidden' name='post_type' value='order' />
            <button type="submit" class="">구매하기</button>
        </form>
        <a href="{% url "store_pad:pad_list" %}"><button>쇼핑계속하기</button></a>
    </div>
    
</div>

{%  endblock %}

cart/templates/pay_complete.html
{% extends 'base.html' %}

{% block main %}
    <h1 style="text-align:center;">결제 성공</h1>
{% endblock %}

cart/templates/pay_now.html
{% extends 'base.html'%}

{% block main%}
<h1 style="text-align:center;">결제진행중</h1>

<script src="http://code.jquery.com/jquery-1.12.4.min.js" ></script>
<script src="http://service.iamport.kr/js/iamport.payment-1.1.5.js"></script>
<script>
(function() {
    var IMP = window.IMP;
    var code = "iamport";  // FIXME: 가맹점 식별코드 (로그인/시스템설정/내정보)
    IMP.init(code);
    // 결제요청
    IMP.request_pay({
        pg : 'html5_inicis', //pg사 변경 가능
        pay_method : 'card',
        merchant_uid : '{{ order.merchant_uid }}',
        name : '{{ order.name }}',
        amount : {{ order.amount }},
        buyer_email : '{{ order.buyer_email }}',
        buyer_name : '{{ order.buyer_name }}',
        buyer_tel : '{{ order.buyer_tel }}',
        //buyer_addr : '서울특별시 강남구 삼성동',
        //buyer_postcode : '123-456',
        m_redirect_url : '{% url "cart:pay_complete" %}'
    }, function(rsp) {
        if ( rsp.success ) {
            var msg = '결제가 완료되었습니다.';
            //msg += '고유ID : ' + rsp.imp_uid; //iamport에서 결정해주는 고유 아이디
            //msg += '상점 거래ID : ' + rsp.merchant_uid; //상점아이디
            //msg += '결제 금액 : ' + rsp.paid_amount;
            //msg += '카드 승인번호 : ' + rsp.apply_num;

            var imp_uid = rsp.imp_uid;
            location.href = '{% url "cart:pay_complete" %}?imp_uid='+imp_uid;
        }
        else {
            var msg = '결제에 실패하였습니다. 에러내용 : ' + rsp.error_msg;
        }
        alert(msg);
    });
})();
</script>

{% endblock %}




<!--  extra body for js-->
<script src="//code.jquery.com/jquery-1.12.4.min.js" ></script>
<script src="https://service.iamport.kr/js/iamport.payment-1.1.5.js"></script>
<script>
$(function() {
    var $form = $('#order-form');
    var params = {
        name: $form.find('[name=name]').val(),
        amount: $form.find('[name=amount]').val(),
    };
    IMP.init('{{ iamport_shop_id }}');
    IMP.request_pay(params, function(response_data) {
        console.log('response_data :', response_data);
        if ( ! response_data.success ) {
            alert(response_data.error_msg + "(" + response_data.error_code + ")");
            location.href = '{% url "store_pad:pad_list" %}';
        }
        else {
            $.each(response_data, function(key, value) {
                $form.find("input[name=" + key + "]").val(value);
            });
            $form.submit();
        }
    }); 
});
</script>

cart/templates/payment.html
{% extends 'base.html'%}

{% block css%}
  <link rel="stylesheet" href="/static/css/login/default.css">
  <link rel="stylesheet" href="/static/css/cart/cart_temp.css">
{% endblock%}

{% block main %}
<div id="main">
    <h1>스토어 주문내역</h1>

    <!-- 장바구니 리스트 -->
    <div class="carttable_container">
        <table class="carttable"style="width:100%">
            <tr>
                <th> </th>
                <th>상품</th>
                <th>가격</th>
                <th>수량</th>
                <th>총가격</th>
            </tr>

            {% for cart_product in cart_products %}
            <tr>
                <td><input type="checkbox" name="" value=""></td>
                <td><img src="{{ cart_product.product.img_front.url }}" width=100px> {{ cart_product.product.name }}</td>
                <td>{{ cart_product.product.price }}원</td>
                <td>X {{ cart_product.order }}</td>
                <td>{{ cart_product.total_price }}원</td>
            </tr>
            {% endfor %}

        </table>
        <a href="{% url "cart:cart" %}">
            <button>주문 변경</button>
        </a>
    </div>

     <form action="" method="POST">
        {% csrf_token %}
        <!-- 주문자 정보 -->
        <div class="user_info">
            <h2>주문자 정보</h2>
            <table>
                <tr>
                    <td>이름</td>
                    <td>{{ form.buyer_name }}</td>
                </tr>
                <tr>
                    <td>이메일</td>
                    <td>{{ form.buyer_email }}</td>
                </tr>
                <tr>
                    <td>휴대폰번호</td>
                    <td>{{ form.buyer_tel }}</td>
                </tr>
                <tr>
                    <td>{{ form.name }}</td>
                    <td>{{ form.amount }}</td>
                </tr>
            </table>
        </div>

        <!-- 배송지 정보 -->
        <div class="address_info">
            <h2>배송지 정보</h2>
            <table>
                <tr>
                    <td>이름</td>
                    <td>{{ form.recipient_name }}</td>
                </tr>
                <tr>
                    <!--TODO: 휴대폰인증-->

                    <td>휴대폰번호</td>

                    <td>{{ form.recipient_tel }}</td>
                </tr>
                <tr>
                    <!--TODO: 주소API-->
                    <td>주소</td>
                    <td>
                        <input name="recipient_postcode" type="text" id="sample6_postcode" placeholder="우편번호">
                        <input type="button" onclick="sample6_execDaumPostcode()" value="우편번호 찾기"><br>
                    </td>
                </tr>

                <tr>
                    <td></td>
                    <td><input name="recipient_add" type="text" id="sample6_address" placeholder="주소"></td>
                </tr>
                <tr>
                    <td></td>
                    <td><input name="recipient_adddetail" type="text" id="sample6_address2" placeholder="상세주소"></td>
                </tr>

{#                    <td>{{ form.recipient_postcode }}</td>#}
{#                    <td>{{ form.recipient_add }}</td>#}

                <tr>

                    <td>배송 메모 (선택)</td>
                    <td>{{ form.recipient_memo }}</td>
                </tr>
            </table>
        </div>

        <!--  결제하기 -->
        <div class="pay">
            <h2>최종 결제금액</h2>
            <table class="total_price">
                <tbody>
                    <tr><td>총 상품가격</td><td>{{ ulti_total_price }}원</td></tr>
                    <tr><td>배송비</td><td>{{ shipping_charge }}원</td></tr>
                    <tr><td>총 결제금액</td><td>{{ amount }}</td></tr>

                </tbody>

            </table>
            <input type='hidden' name='post_type' value='pay' />
            <button type="submit" class="">결제하기</button>
        </div>
    </form>



</div>

    <!-- 다음주소 API -->
    <script src="http://dmaps.daum.net/map_js_init/postcode.v2.js"></script>

    <script>
        function sample6_execDaumPostcode() {
            new daum.Postcode({
                oncomplete: function(data) {
                    // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.
                    // 각 주소의 노출 규칙에 따라 주소를 조합한다.
                    // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.
                    var fullAddr = ''; // 최종 주소 변수
                    var extraAddr = ''; // 조합형 주소 변수
                    // 사용자가 선택한 주소 타입에 따라 해당 주소 값을 가져온다.
                    if (data.userSelectedType === 'R') { // 사용자가 도로명 주소를 선택했을 경우
                        fullAddr = data.roadAddress;
                    } else { // 사용자가 지번 주소를 선택했을 경우(J)
                        fullAddr = data.jibunAddress;
                    }
                    // 사용자가 선택한 주소가 도로명 타입일때 조합한다.
                    if(data.userSelectedType === 'R'){
                        //법정동명이 있을 경우 추가한다.
                        if(data.bname !== ''){
                            extraAddr += data.bname;
                        }
                        // 건물명이 있을 경우 추가한다.
                        if(data.buildingName !== ''){
                            extraAddr += (extraAddr !== '' ? ', ' + data.buildingName : data.buildingName);
                        }
                        // 조합형주소의 유무에 따라 양쪽에 괄호를 추가하여 최종 주소를 만든다.
                        fullAddr += (extraAddr !== '' ? ' ('+ extraAddr +')' : '');
                    }
                    // 우편번호와 주소 정보를 해당 필드에 넣는다.
                    document.getElementById('sample6_postcode').value = data.zonecode; //5자리 새우편번호 사용
                    document.getElementById('sample6_address').value = fullAddr;
                    // 커서를 상세주소 필드로 이동한다.
                    document.getElementById('sample6_address2').focus();
                }
            }).open();
        }
    </script>

{% endblock %}

cart/templates/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
성공
</body>
</html>